### ISSUE TITLE
Suggestion: allow console to force-RTP other players

### ISSUE THREAD

**Issue by lokka30** [JakeTS/JakesRTP#1]

**Comment by JakeTS** [comment]
I know I already answered on the spigot forms, but the answer was to use the `forcertp` command:
`forcertp <playerName> [-c <rtpConfigName> | -w <destinedWorld> | -c-w <rtpConfigName> <destinedWorld>]`
And to note again, I use these `[ ]` even though the second argument groups is required just to make it easier to read.
